version: "3.7"

services:

    app:
        build:
          dockerfile: .docker/app/Dockerfile
          context: .
          target: dev
        container_name: micro-videos-app
        entrypoint: dockerize -template /templates/.env:/var/www/backend/.env -template /templates/.env.testing:/var/www/backend/.env.testing -wait tcp://db:3306 -timeout 40s /entrypoint.sh
        ports:
            - "3000:3000"
            - "35729:35729"
        environment:
            - _DB_HOST=db
            - _DB_DATABASE=code_micro_videos
            - _DB_USERNAME=root
            - _DB_PASSWORD=root
            - _TEST_DB_DATABASE=code_micro_videos_test
            - CHOKIDAR_USEPOLLING=true
        volumes:
            - ./www:/var/www
        networks:
            - app-network
        depends_on:
            - db
            - redis

    nginx:
        build: .docker/nginx
        container_name: micro-videos-nginx
        restart: always
        tty: true
        ports:
            - "8000:80"
        volumes:
            - ./www:/var/www
        networks:
            - app-network
        depends_on:
            - app

    db:
        build: ./.docker/mysql
        container_name: micro-videos-db
        restart: always
        tty: true
        ports:
            - "33006:3306"
        volumes:
            - ./.docker/dbdata:/var/lib/mysql
            - ./.docker/mysql:/docker-entrypoint-initdb.d
        environment:
            #- MYSQL_DATABASE=code_micro_videos
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
        networks:
            - app-network

    redis:
        image: redis:alpine
        container_name: micro-videos-redis
        expose:
            - 6379
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
